name: Publish to Prd
on: 
  push:
    branches:
      - master
    paths:
      - 'enfold-child/**'

jobs:
  FTP-Deploy-To-Prd:
    name: FTP-Deploy-To-Prd
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-To-Prd
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        local-dir: enfold-child/
        ftp-server: ${{ secrets.FTP_SERVER_PRD }}
        ftp-username: ${{ secrets.FTP_USER_PRD }}
        ftp-password: ${{ secrets.FTP_PASSWORD_PRD }}
        git-ftp-args: --insecure

        
